-- AURA Care Database Schema for Supabase
-- Designed for Clerk authentication (uses Clerk user IDs as text PKs)
-- Supports one-to-one caregiver <-> senior relationships

-- ============================================================
-- CLEANUP: Drop old tables/triggers/functions from previous schema
-- ============================================================
DROP FUNCTION IF EXISTS update_updated_at() CASCADE;

DROP TABLE IF EXISTS extracted_medications CASCADE;
DROP TABLE IF EXISTS prescription_scans CASCADE;
DROP TABLE IF EXISTS medication_schedules CASCADE;
DROP TABLE IF EXISTS medications CASCADE;
DROP TABLE IF EXISTS meals CASCADE;
DROP TABLE IF EXISTS wellbeing_checkins CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS caregiver_seniors CASCADE;
DROP TABLE IF EXISTS caregiver_senior_links CASCADE;
DROP TABLE IF EXISTS pairing_codes CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS caregivers CASCADE;
DROP TABLE IF EXISTS seniors CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- 1. USERS — stores Clerk user profile + chosen role
-- ============================================================
CREATE TABLE users (
  clerk_id    TEXT PRIMARY KEY,              -- Clerk userId e.g. "user_2x..."
  name        TEXT NOT NULL DEFAULT 'User',
  role        TEXT CHECK (role IN ('senior', 'caregiver')),
  language    TEXT NOT NULL DEFAULT 'en',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. PAIRING_CODES — 6-digit codes generated by caregivers
--    Single-use: once a senior claims it, is_claimed = true
-- ============================================================
CREATE TABLE pairing_codes (
  code          TEXT PRIMARY KEY,             -- e.g. "482917"
  caregiver_id  TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  caregiver_name TEXT NOT NULL DEFAULT 'Caregiver',
  is_claimed    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pairing_codes_caregiver ON pairing_codes(caregiver_id);

-- ============================================================
-- 3. CAREGIVER_SENIOR_LINKS — one-to-one pairing table
--    Created when a senior claims a pairing code
--    Each caregiver has at most one senior, each senior has at most one caregiver
-- ============================================================
CREATE TABLE caregiver_senior_links (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code            TEXT NOT NULL REFERENCES pairing_codes(code),
  caregiver_id    TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  caregiver_name  TEXT NOT NULL DEFAULT 'Caregiver',
  senior_id       TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  senior_name     TEXT NOT NULL DEFAULT 'Senior',
  linked_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(caregiver_id),
  UNIQUE(senior_id)
);

CREATE INDEX IF NOT EXISTS idx_links_caregiver ON caregiver_senior_links(caregiver_id);
CREATE INDEX IF NOT EXISTS idx_links_senior ON caregiver_senior_links(senior_id);

-- ============================================================
-- 4. MEDICINES — per-senior, uploaded by a caregiver
--    "taken" resets daily (or per-session for MVP)
-- ============================================================
CREATE TABLE medicines (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  senior_id         TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  uploaded_by       TEXT REFERENCES users(clerk_id) ON DELETE SET NULL,
  name              TEXT NOT NULL,
  name_hi           TEXT NOT NULL DEFAULT '',
  dosage            TEXT NOT NULL DEFAULT '',
  frequency         TEXT NOT NULL DEFAULT '',
  timing            TEXT NOT NULL DEFAULT '',
  before_after_food TEXT NOT NULL DEFAULT 'any'
                    CHECK (before_after_food IN ('before', 'after', 'with', 'any')),
  taken             BOOLEAN NOT NULL DEFAULT FALSE,
  taken_at          TIMESTAMPTZ,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_medicines_senior ON medicines(senior_id);
CREATE INDEX IF NOT EXISTS idx_medicines_uploader ON medicines(uploaded_by);

-- ============================================================
-- 5. WELLBEING_CHECKINS — senior mood/pain check-ins
--    Latest row per senior = current status
-- ============================================================
CREATE TABLE wellbeing_checkins (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  senior_id   TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  mood        TEXT NOT NULL CHECK (mood IN ('good', 'okay', 'not_well')),
  pain_area   TEXT,                           -- NULL if mood != 'not_well'
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wellbeing_senior ON wellbeing_checkins(senior_id);
CREATE INDEX IF NOT EXISTS idx_wellbeing_latest ON wellbeing_checkins(senior_id, created_at DESC);

-- ============================================================
-- 6. ALERTS — notifications visible to linked caregivers
-- ============================================================
CREATE TABLE alerts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  senior_id   TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  type        TEXT NOT NULL CHECK (type IN ('medication', 'inactivity', 'distress', 'offline')),
  message     TEXT NOT NULL,
  message_hi  TEXT NOT NULL DEFAULT '',
  time_label  TEXT NOT NULL DEFAULT '',       -- display string e.g. "2:30 PM"
  severity    TEXT NOT NULL DEFAULT 'info'
              CHECK (severity IN ('critical', 'warning', 'info')),
  is_read     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_senior ON alerts(senior_id);

-- ============================================================
-- 7. MEDICINE_LOGS — permanent history of every medicine take
--    One row per medicine per day. Never deleted.
-- ============================================================
DROP TABLE IF EXISTS medicine_logs CASCADE;

CREATE TABLE medicine_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  senior_id     TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  medicine_id   UUID NOT NULL REFERENCES medicines(id) ON DELETE CASCADE,
  medicine_name TEXT NOT NULL,
  dosage        TEXT NOT NULL DEFAULT '',
  taken_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  taken_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(medicine_id, taken_date)   -- one log per medicine per day
);

CREATE INDEX IF NOT EXISTS idx_medicine_logs_senior ON medicine_logs(senior_id);
CREATE INDEX IF NOT EXISTS idx_medicine_logs_date ON medicine_logs(senior_id, taken_date DESC);

-- ============================================================
-- 8. MEAL_LOGS — permanent history of meal check-ins
-- ============================================================
DROP TABLE IF EXISTS meal_logs CASCADE;

CREATE TABLE meal_logs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  senior_id   TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
  meal_type   TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')),
  eaten       BOOLEAN NOT NULL DEFAULT TRUE,
  log_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(senior_id, meal_type, log_date)  -- one log per meal per day
);

CREATE INDEX IF NOT EXISTS idx_meal_logs_senior ON meal_logs(senior_id);
CREATE INDEX IF NOT EXISTS idx_meal_logs_date ON meal_logs(senior_id, log_date DESC);

-- ============================================================
-- ROW LEVEL SECURITY
-- Using permissive "public" policies for MVP/demo.
-- In production, replace with Clerk JWT verification.
-- ============================================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pairing_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE caregiver_senior_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE wellbeing_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_logs ENABLE ROW LEVEL SECURITY;

-- Users
CREATE POLICY "users_all" ON users FOR ALL USING (true) WITH CHECK (true);

-- Pairing codes
CREATE POLICY "pairing_codes_all" ON pairing_codes FOR ALL USING (true) WITH CHECK (true);

-- Links
CREATE POLICY "links_all" ON caregiver_senior_links FOR ALL USING (true) WITH CHECK (true);

-- Medicines
CREATE POLICY "medicines_all" ON medicines FOR ALL USING (true) WITH CHECK (true);

-- Wellbeing
CREATE POLICY "wellbeing_all" ON wellbeing_checkins FOR ALL USING (true) WITH CHECK (true);

-- Alerts
CREATE POLICY "alerts_all" ON alerts FOR ALL USING (true) WITH CHECK (true);

-- Medicine logs
CREATE POLICY "medicine_logs_all" ON medicine_logs FOR ALL USING (true) WITH CHECK (true);

-- Meal logs
CREATE POLICY "meal_logs_all" ON meal_logs FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- TRIGGER: auto-update updated_at on users
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();
